
s = "CTGTACCGATTTACGTGGGTCTTAAATGAGTGATTCGACATAAGGCGGCTTTAGAGCGTAAGGTGGGTGTCGTTTCCTAGGCCAATACAACGCCTTTTATTTCATATGAACTCCTGTAATCCAGGAATCATAGGCGGTTTCCATTACTACGTATATACAAGATTACCTGCCCGTACCTATAGATCGCTTCGCTGCGTGTCAAGGACACAGCGGACATGGGATGCACGACCCGGGCGGGTATAGGTTTTTACTGCGTGCCGTCAAATTGTGACTGTCTGACTAAGCCCCGACACATTAGTGCGTCTATATCAAATAATTTGGGGCTAACCGCCTAGCATCTTAGAACGGGGTATATTACATCCTTTTGTCTCATCCTAGCCTAGGAATCAGCGTCGTATGCTGCCAAGGACTAGCGATTCTAAAAGTCATTGTGGAAGTAGCAAGGCCGGGCCCAGAGTGAACACCGTTCATTAGACTGTTCGATGGCCCCGAACGCACTCCGTCTTCGATAGAATAGTGTGCTCATTCTGGGTTATAGAGCAGCGTCGTGATACATTAGTTCAGCAAGAAGGCTCCGGTGATGGTAATGGAGCAGTGAAGTGCTGTACAAGGTGTCGGGGTACGCCGTCTAACGGGTAAGAATCTCCTCGCGACTTAACACAATCCACACCGATACCAGTCTACGATATTGGGAACAAGTCGTCGGAGACTGTCCCTAGGGGACTTGATGGTTGTCTCAGTAGTAGCCTCTAGCGATCCGCTAAACTCGACTGCTTGGCCGGTGACCGATCCCGCCAAGTGGCAATTAATCTTCGATGCACATGACTTCCGTCTACCGGAGCCGAGGAACTATGAGGTAGTTCGGTAAGTCCTGGAACGGCCCCAAATAGCATCTGCATCCCGGTCTTGGAGCTATTGAGTGCCAGCAGGTTGCTGTCAAGCG"
a = 0
c = 0
g = 0
t = 0

for x in s:
    if x == 'A':
        a += 1
    elif x == 'C':
        c += 1
    elif x == 'G':
        g += 1
    elif x == 'T':
        t += 1

print(str(a) + ' ' + str(c) + ' ' + str(g) + ' ' + str(t))